<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 1,
                'sub_sub_category_id' => 1,
                'product_name' => 'Smartphone X',
                'product_slug' => 'smartphone-x',
                'product_code' => 'SPX001',
                'product_quantity' => 50,
                'product_tags' => 'electronics,smartphone,mobile',
                'product_size' => 'M',
                'product_colour' => 'Black',
                'product_selling_price' => 699,
                'product_discount_price' => 649,
                'product_short_desc' => 'Latest Smartphone X with amazing features.',
                'product_long_desc' => 'Smartphone X features a 6.5 inch display, high-res camera, and long-lasting battery.',
                'product_thumbnail' => 'product1_thumb.jpg',
                'hot_deal' => 1,
                'featured' => 0,
                'special_offer' => 0,
                'special_deals' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 2,
                'category_id' => 2,
                'sub_category_id' => 2,
                'sub_sub_category_id' => 2,
                'product_name' => 'Running Shoes',
                'product_slug' => 'running-shoes',
                'product_code' => 'RS002',
                'product_quantity' => 80,
                'product_tags' => 'sports,shoes,running',
                'product_size' => 'L',
                'product_colour' => 'Red',
                'product_selling_price' => 120,
                'product_discount_price' => 100,
                'product_short_desc' => 'Comfortable running shoes for all terrains.',
                'product_long_desc' => 'These running shoes provide excellent grip and comfort for long distances.',
                'product_thumbnail' => 'product2_thumb.jpg',
                'hot_deal' => 0,
                'featured' => 1,
                'special_offer' => 1,
                'special_deals' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 3,
                'category_id' => 3,
                'sub_category_id' => 3,
                'sub_sub_category_id' => 3,
                'product_name' => 'Blender Pro',
                'product_slug' => 'blender-pro',
                'product_code' => 'BLD003',
                'product_quantity' => 40,
                'product_tags' => 'kitchen,appliance,blender',
                'product_size' => 'One Size',
                'product_colour' => 'White',
                'product_selling_price' => 150,
                'product_discount_price' => 130,
                'product_short_desc' => 'Powerful blender for smooth and juices.',
                'product_long_desc' => 'Blender Pro crushes ice, blends fruits, and makes smoothies with ease.',
                'product_thumbnail' => 'product3_thumb.jpg',
                'hot_deal' => 0,
                'featured' => 0,
                'special_offer' => 1,
                'special_deals' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 4,
                'category_id' => 4,
                'sub_category_id' => 4,
                'sub_sub_category_id' => 4,
                'product_name' => 'Classic Novel',
                'product_slug' => 'classic-novel',
                'product_code' => 'BK004',
                'product_quantity' => 100,
                'product_tags' => 'books,classic,novel',
                'product_size' => 'N/A',
                'product_colour' => 'N/A',
                'product_selling_price' => 25,
                'product_discount_price' => 20,
                'product_short_desc' => 'A timeless classic novel loved by readers.',
                'product_long_desc' => 'This classic novel is a masterpiece of literature, perfect for any collection.',
                'product_thumbnail' => 'product4_thumb.jpg',
                'hot_deal' => 0,
                'featured' => 1,
                'special_offer' => 0,
                'special_deals' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'brand_id' => 5,
                'category_id' => 5,
                'sub_category_id' => 5,
                'sub_sub_category_id' => 5,
                'product_name' => 'Yoga Mat',
                'product_slug' => 'yoga-mat',
                'product_code' => 'YM005',
                'product_quantity' => 60,
                'product_tags' => 'sports,yoga,mat',
                'product_size' => 'Standard',
                'product_colour' => 'Green',
                'product_selling_price' => 45,
                'product_discount_price' => 40,
                'product_short_desc' => 'Durable and comfortable yoga mat.',
                'product_long_desc' => 'This yoga mat provides excellent grip and cushioning for all yoga levels.',
                'product_thumbnail' => 'product5_thumb.jpg',
                'hot_deal' => 1,
                'featured' => 0,
                'special_offer' => 1,
                'special_deals' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
